### ISSUE TITLE
Most efficient way to check for live broadcasts from specific users?

### ISSUE THREAD

**Issue by wlerin** [ping/instagram_private_api#10]
### Before submitting an issue, make sure you have:
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Live Broadcast Notifications

It's been a few weeks since I looked at this in detail, but I didn't see any lightweight "**are these users streaming right now**" endpoint. There's two slightly different ways of getting suggested/popular streams (`discover_top_live`, `suggested_broadcasts`), and I can check users individually through `user_story_feed`, but there doesn't seem to be an equivalent of the latter for multiple users (like `reels_media` but including broadcasts). Or did I miss something?

`top_live_status` looks promising, but I've no idea how broadcast ids map to users.

Ideally I'd like something I can check fairly frequently throughout the day.

**Comment by ping** [comment]
``top_live_status()`` doesn't work because you need to already have the broadcast IDs. The endpoint is used for updating the "explore wall" of top live streams.

If you follow those specific users, ``reels_tray()`` should return their broadcasts if they are streaming now. Otherwise like you said, you must poll ``user_story_feed()`` individually.

**Comment by wlerin** [comment]
Alright, I'll try out `reels_tray()` and see how it works.

Unrelated, have you considered using the python-requests library instead of raw httplib? I suspect the connection pool alone would significantly improve performance. I looked at converting the api a while back, the biggest issues would probably be error handling (since Requests uses many different Exceptions where httplib only uses like three) and the `uploads` and `account` endpoints since they make their own requests without going through `_call_api`. 

Was going to make a separate issue about it but I haven't had the time to work on it, and you're actively developing other features.

**Comment by ping** [comment]
I have thought about it but it's not likely something to be coming soon, nor am I very enthused about it for a few reasons.

1. Partly because of my own use case since I do not use the lib in a long-running multiple-call manner.

```
- Init api
- Call 1 method
- Do my stuff
- Exit
```

So the absolute upside with connection pooling is limited for me. As I see it, only media posting (especially videos) will gain significantly from using ``requests`` because of the multiple calls needed per posting.

2. It's also a matter of personal preference. ``requests`` (very nicely) abstracts away the nitty gritty of making the http requests, this is great in most cases but because I need to make sure that individual requests match up with those from the official app, the abstraction can be a bit of a hindrance. For example, in multipart posts, there is a need to specify the "boundary" which if I'm not mistaken is not supported ootb in requests (requires toolbelt). This is not insurmountable obviously, it's just a preference derived from how I reverse engineer the app and translate that into code in the lib.

A switch to ``requests`` if it happens, needs to go into a v2 release with appropriate migration options mapped out. At this point, it's not work I want to undertake or support.

All that said, I think ``requests`` is awesome and I use it in the companion [extensions module](https://github.com/ping/instagram_private_api_extensions) for downloading live streams (which is very time sensitive and the connection pooling dramatically improves performance).

I'm totally okay with people forking and taking the ``requests`` route, especially if the perf improvements are tangible for them.

_(With regards to the exceptions, the current lib doesn't bother handling many of the connection/transport level errors like ``ssl.SSLError``, ``socket.timeout``, ``socket.error``, ``urllib2.URLError/urllib.error.URLError``,  ``httplib.HTTPException/http.client.HTTPException`` either since I left it to the implementor. It's debatable whether that's a good choice but it is what it is right now. The ``requests`` exceptions are probably much easier to work with wrt this.)_

**Comment by wlerin** [comment]
Understandable I guess. Unfortunately my intended use case involves regularly checking multiple accounts for updates throughout the day, possibly with a persistent state. Guess I'll have to figure out how to fork it while staying up to date.
