### ISSUE TITLE
Make the App Client Asynchronous using asyncio

### ISSUE THREAD

**Issue by b3nab** [ping/instagram_private_api#119]
### Before submitting the issue, I'm sure that I have:
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe your Feature Request:

The feature description is really simple to express, I want to use this library within an asyncio loop, and to do so it need to be asynchronous to use asyncio at full power, otherwise it would block the loop until the request is done.

You could suggest me to spawn a subprocess or do some multithread stuffs, but I think that asyncio is the future of Python and the implementation of `async`, `await` in Python language is an important direction of where we will go in the future.

I think that we could make the client async with just a few more line of code, and without make any breaking change, so who won't want to use asyncio features can doing that in the "legacy" (old) way.

**Comment by wlerin** [comment]
What you ask is a huge undertaking and would require a separate library, rather than being just "a few more line of code". Additionally, asyncio doesn't exist on Python 2, and this library goes out of its way to maintain compatibility with 2.7 (to the point I suspect the author does most of his development and testing on 2.7).

I'd suggest either forking the project and trying to write it yourself, or using established methods of running blocking calls within an async loop.

**Comment by ping** [comment]
I'll be open to see a working fork with demonstrable python compatibility (>=2.7) and current tests passing.
