### ISSUE TITLE
examples\pagination.py error

### ISSUE THREAD

**Issue by gregkr** [ping/instagram_private_api#144]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

Paste the output of ``python -V`` here:

Code:

```D:\...\instagram_private_api-master>python -V
Python 2.7.15

# Example code that will produce the error reported
D:\...\instagram_private_api-master>examples\pagination.py -u ry***k -p R***8
Client version: 1.6.0
Traceback (most recent call last):
  File "D:\pjx\instagram_private_api\instagram_private_api-master\examples\pagination.py", line 38, in <module>
    results = api.user_followers(user_id)
TypeError: user_followers() takes exactly 3 arguments (2 given)

```

**Comment by wlerin** [comment]
This and #145 are basically the same issue.

It seems like the max_id method still works when called directly against the API, but for some reason `user_followers` and `tag_search` (#145)--and perhaps others--*require* a `rank_token`, both because it's a positional argument and because they then check if the rank token is valid (and None is invalid).

As far as I can tell, either `rank_token` or `max_id`, or neither, should be allowed by both methods.

**Comment by gregkr** [comment]
Thank you for your explanation. 
But please either indicate what my mistake is or correct yours.
