### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by danielleontiev** [ping/instagram_private_api#30]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.3.6
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

I can see that proxy support now is alpha. What kind of issues I'll face and what carefully should I look for?

**Comment by NoLogick** [comment]
It definitely works. I use 1000+ accounts with https proxies (+authenthication login:pass). All my accs are alive. So, I don't see any problem with proxy support. I think it's alpha because there is no way to test this feature to be 100% sure. Instagram doesn't return user's IP address.

**Comment by NoLogick** [comment]
It definitely works. I use 1000+ accounts with https proxies (+authenthication login:pass). All my accs are alive. So, I don't see any problem with proxy support. I think it's alpha because there is no way to test this feature to be 100% sure. Instagram doesn't return user's IP address.

Here simple test code same as in client.py:

`from instagram_private_api.compat import compat_urllib_parse_urlparse, compat_urllib_request

proxy = 'https://login:pass@127.0.0.1:3128/'

parsed_url = compat_urllib_parse_urlparse(proxy)
if parsed_url.netloc and parsed_url.scheme:
    proxy_address = '{0!s}://{1!s}'.format(parsed_url.scheme, parsed_url.netloc)
    proxy_handler = compat_urllib_request.ProxyHandler({'https': proxy_address})
else:
    raise ValueError('Invalid proxy argument: {0!s}'.format(proxy))

opener = compat_urllib_request.build_opener(proxy_handler)

req = compat_urllib_request.Request('https://httpbin.org/ip')
with opener.open(req) as f:
    print(f.read())` 

You will see your proxy IP.

**Comment by danielleontiev** [comment]
@NoLogick thanks a lot!
Now I've tested proxy with my accounts and it works like a charm.
