### ISSUE TITLE
Most efficient way to check if user following you

### ISSUE THREAD

**Issue by nivexz** [ping/instagram_private_api#37]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.3.6
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Hi, I want my program to check if a user is following another user.
The input will be for example user "X" and then I check "Y" is followed by "X"/
Of course there are 2 ways to get to this, one by checking the following list of "X", and the second is checking the followers list of "Y".
Assuming that I want to use second method (Check in followers of "Y") what is the best way ? On Instagram real app there is a feature of follower search. I though about taking all the followers list of Y and check if "X" is in the list. but what if it is an account of 100K+ followers ?

Thank you !

**Comment by ping** [comment]
Only an authenticated user can check his/her friendship status with another account with ``friendships_show()``. 

There is no function to check friendship status between 2 accounts.

**Comment by umeta77** [comment]
Just to revive this topic with a bit more information on the subject. While it may be true that there isn't a function in this project there most certainly is an endpoint _somewhere_ in the private API to search the followers of another user because it's right there in official IG apps (sans web app).

Seen below is an example on iOS. As a logged in user I can visit Ryan Reynolds' profile, click on his followers and search for any username. The same can be done in reverse, therefore determining one-way or mutual friendships/follows without being authenticated as either of those users. 

![ios-follower-search](https://user-images.githubusercontent.com/66185245/83339637-88f7f600-a295-11ea-959c-d62af1781917.png)

See also https://mashable.com/2016/03/28/instagram-search-followers-following/

I myself have been trying to determine what call is being called for this but haven't been able to sniff it out with Charles just yet. @ping If this can be figured out is it something the maintainers would be interested in adding to this project?

**Comment by HE1CO** [comment]
@umeta77 Simply use the query parameter with the userid for user_followers()
