### ISSUE TITLE
web_blocking exception in response of new accounts request

### ISSUE THREAD

**Issue by SinaKhorami** [ping/instagram_private_api#96]
- [x] Updated to the lastest version v1.5.7
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

- [ ] app (``instagram_private_api/``)
- [x] web (``instagram_web_api/``)

---

### Describe the Bug/Error:

I recently created instagram account and with the help of `media_comments` route i am able to fetch comments of my specified post. I tried to run this on my VPS which i bought from hetzner but i faced the `Expecting value: line 1 column 1 (char 0)` exception.
After some experience with built-in code of `media_comments` i noticed the issue is coming from the line which is `return json.loads(response_content)`. so i checked the response_content and it's an HTML that i pasted [here](https://paste.ubuntu.com/p/K2vrKpk8Gf/).
```json
"TermsUnblockPage": [{
    "data": {
        "screen_key": "web_blocking",
        "contents": {
            "web_blocking": {
                "consent_key": "web_blocking",
                "content_type": "text",
                "headline": "Updates to Our Terms and Data Policy",
                "paragraphs": [{
                    "text": "We've updated our Terms and made some changes to our Data Policy. Please take a moment to review these changes and let us know that you agree to them.",
                    "style": "paragraph"
                }, {
                    "text": "You need to finish reviewing this information before you can use Instagram.",
                    "style": "paragraph"
                }],
                "optional_paragraphs": []
            }
        },
        "primary_button_text": "Review Now",
        "launch_flow_directly": true
    },
    "__USE_DEPRECATED_API_SERIALIZER": true
}]
```
I can successfully get the response via my old instagram username and password but the new accounts have this issue.

**Comment by notcammy** [comment]
Try logging in on the new accounts on a webbrowser or phone and agree on the new terms of service if you haven't already

**Comment by SinaKhorami** [comment]
@notcammy I can login on my phone and even from browser without any problems and there is no new terms of service to agree. I have this problem on the server not in my local. Also tried to use some terminal browser such as lynx to login instagram via my server but no success.

**Comment by ping** [comment]
This may be linked to GDPR since you're connecting via a European host. You will need to manually accept the new TOS connected  through your browser via the same IP or another European location. Or just don't use a European host.

**Comment by MrSwilix** [comment]
These errors occur when connecting via a European host because your Instagram profile is localized in a city governed by **GDPR** (General Data Protection Regulation). This is incompatible with the  [instagram_private_api](https://github.com/ping/instagram_private_api) montioned in the README.md file used by the  [Osintgram.py](https://github.com/Datalux/Osintgram/blob/master/src/Osintgram.py) file code Line 14 - 15.

```python
from instagram_private_api import Client as AppClient
``` 
```python
from instagram_private_api import ClientCookieExpiredError, ClientLoginRequiredError, ClientError, ClientThrottledError
``` 


To resolve this issue, you must avoid using a European IP. Instead, create a new Instagram profile using an IP address, phone number, and email located in a non-European country, such as the USA or any other country not governed by GDPR regulations. This will prevent potential access issues to Instagram for your Instagram Private API

Please validate and close the issue if this answered your error! , this will help the developers and users of this tool who want to resolve the problem, thank you!
